version: '3'

services:
  # MongoDB service
  mongo:
    image: mongo:latest
    container_name: amalgamator-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - amalgamator-network

  # Backend service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: amalgamator-backend
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/amalgamator
      - JWT_SECRET=your_jwt_secret_key
      - NODE_ENV=production
      - PORT=5000
    networks:
      - amalgamator-network

  # Frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: amalgamator-frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
    networks:
      - amalgamator-network

networks:
  amalgamator-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
